psql: &psql
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
  pool: 5

development:
  <<: *psql
  database: hiddn_development

test:
  <<: *psql
  database: hiddn_test
